import { describe,it,expect } from 'vitest';
import { ensurePromptTags,renamePromptTag,replacePhoto,movePhoto } from './tags';
import { newShot, type Project, type Asset } from './model';
const asset=(id:string,name:string):Asset=>({id,name,media_type:'image',role:'reference_image',semantic_role:'wardrobe',enabled:true,locked_order:false,description:'clothes only',observation:'old',approved_observation:'old'});
const make=()=>({schema_version:1,id:'p',title:'Demo',mode:'ref2va',duration:5,aspect_ratio:'16:9',profile:'concise',authoring_mode:'full',story:{text:'Use @green-dress beside @green-dress-2. Email a@green-dress.test',locked:true},style:{},assets:[asset('a','Green Dress'),asset('b','Green Dress')],subjects:[{id:'s',name:'Mira',asset_ids:['a'],description:''}],shots:[newShot()],soundscape:'',music:'',custom_instructions:''}) as Project;
describe('stable photo references',()=>{
  it('creates readable unique tags that survive name and order changes',()=>{const p=make();ensurePromptTags(p);expect(p.assets.map(a=>a.prompt_tag)).toEqual(['green-dress','green-dress-2']);p.assets[0].name='Other';movePhoto(p,'a',1);ensurePromptTags(p);expect(p.assets[1].prompt_tag).toBe('green-dress');});
  it('renames exact prose mentions without changing dialogue, emails or longer tags',()=>{const p=make();ensurePromptTags(p);p.shots[0].dialogue=[{text:'Say @green-dress literally.'}];renamePromptTag(p,'a','emerald');expect(p.story.text).toBe('Use @emerald beside @green-dress-2. Email a@green-dress.test');expect(p.shots[0].dialogue[0].text).toBe('Say @green-dress literally.');});
  it('rejects duplicates and malformed tags without mutations',()=>{const p=make();ensurePromptTags(p);const before=structuredClone(p);expect(()=>renamePromptTag(p,'a','green-dress-2')).toThrow();expect(()=>renamePromptTag(p,'a','3 invalid')).toThrow();expect(p).toEqual(before);});
  it('keeps URL path tags and escaped literal handles unchanged',()=>{const p=make();ensurePromptTags(p);p.story.text='https://example.com/@green-dress \\@green-dress @green-dress';renamePromptTag(p,'a','emerald');expect(p.story.text).toBe('https://example.com/@green-dress \\@green-dress @emerald');});
  it('replacement preserves ownership, role and tag, rebinds identity, and discards old image captions',()=>{const p=make();ensurePromptTags(p);p.assets[0].simple_owner_id='s';p.simple={previous_image_roles:{a:'reference_image'}};replacePhoto(p,'a',asset('new','Upload'));expect(p.subjects[0].asset_ids).toEqual(['new']);expect(p.assets[0]).toMatchObject({id:'new',prompt_tag:'green-dress',simple_owner_id:'s',approved_observation:'',observation:'',name:'Green Dress'});expect(p.simple.previous_image_roles).toEqual({new:'reference_image'});});
});
